version: 2
jobs:
  build:
    docker:
      - image: circleci/node:16
    working_directory: ~/repo
    steps:
      - checkout
      - run: npm i --legacy-peer-deps
      - run: npm run build
      - run: bash <(curl -s https://codecov.io/bash)
